language:   ruby
rvm:
    - "1.8.7"
    - "1.9.3"
    - "2.0.0"
    - "2.1.5"
    - "jruby-1.7.17"
env:
    - PARCELS_SPECS_SPROCKETS_VERSION=2.11.3 PARCELS_SPECS_RAILS_VERSION=4.1.7
    - PARCELS_SPECS_SPROCKETS_VERSION=2.11.3 PARCELS_SPECS_RAILS_VERSION=4.0.11
    - PARCELS_SPECS_SPROCKETS_VERSION=2.2.3 PARCELS_SPECS_RAILS_VERSION=3.2.21
    - PARCELS_SPECS_SPROCKETS_VERSION=2.0.5 PARCELS_SPECS_RAILS_VERSION=3.1.12
before_script:
    - export JRUBY_OPTS="$JRUBY_OPTS -J-Xmx256m -J-Xms256m -J-Xss2048k"
matrix:
    exclude:
        # Rails 4.x doesn't support Ruby 1.8.7
        -   rvm: 1.8.7
            env: PARCELS_SPECS_SPROCKETS_VERSION=2.11.3 PARCELS_SPECS_RAILS_VERSION=4.1.7
        -   rvm: 1.8.7
            env: PARCELS_SPECS_SPROCKETS_VERSION=2.11.3 PARCELS_SPECS_RAILS_VERSION=4.0.11
