language:   ruby
rvm:
    - "1.8.7"
    - "1.9.3"
    - "2.0.0"
    - "2.1.5"
    - "jruby-1.7.17"
env:
    - PARCELS_SPECS_SPROCKETS_VERSION=2.11.3 PARCELS_SPECS_RAILS_VERSION=4.1.7
    - PARCELS_SPECS_SPROCKETS_VERSION=2.11.3 PARCELS_SPECS_RAILS_VERSION=4.0.11
    - PARCELS_SPECS_SPROCKETS_VERSION=2.2.3 PARCELS_SPECS_RAILS_VERSION=3.2.21
    - PARCELS_SPECS_SPROCKETS_VERSION=2.0.5 PARCELS_SPECS_RAILS_VERSION=3.1.12
before_script:
    - export JRUBY_OPTS="$JRUBY_OPTS -J-Xmx384m -J-Xms384m -J-Xss2048k"
matrix:
    exclude:
        # Rails 4.x doesn't support Ruby 1.8.7
        -   rvm: 1.8.7
            env: PARCELS_SPECS_SPROCKETS_VERSION=2.11.3 PARCELS_SPECS_RAILS_VERSION=4.1.7
        -   rvm: 1.8.7
            env: PARCELS_SPECS_SPROCKETS_VERSION=2.11.3 PARCELS_SPECS_RAILS_VERSION=4.0.11
    allow_failures:
        # 2014-12-14 ageweke -- Unfortunately, there appears to be a bug in Ruby 1.8.7 that conflicts with Sass and
        # is biting us here. The symptom is that our out-of-process Rails server suddenly crashes, causing various
        # Rails specs to fail with 'connection refused' or 'end of file' (when reading from the socket) kinds of
        # errors. If you look in log/rails-server.log in the Rails server directory, you'll see something like
        # this:
        #
        # : [BUG] gc_sweep(): unknown data type 0x0(0x109cd5fa0)
        # ruby 1.8.7 (2013-06-27 patchlevel 374) [i686-darwin14.0.0]
        #
        # There are multiple sources
        # (https://stackoverflow.com/questions/3844794/server-failure-bug-gc-sweep-unknown-data-type-0x0,
        #  https://github.com/sass/sass/issues/581, etc.)
        # indicating that other people have hit this repeatedly, and we don't seem to ever see it on other Ruby
        # versions.
        #
        # Since 1.8.7 is very old as of this writing, while I'd like to keep officially supporting it, I'm going to
        # keep running these tests but monitor them manually, to see if anything *other* than the Rails specs
        # starts failing.
        -   rvm: 1.8.7
            env: PARCELS_SPECS_SPROCKETS_VERSION=2.2.3 PARCELS_SPECS_RAILS_VERSION=3.2.21
        -   rvm: 1.8.7
            env: PARCELS_SPECS_SPROCKETS_VERSION=2.0.5 PARCELS_SPECS_RAILS_VERSION=3.1.12
